### ISSUE TITLE
Qt5 obsolete functions

### ISSUE THREAD

**Issue by leochan2009** [QIICR/SlicerDevelopmentToolbox#29]
setResizeMode is not available any more, should be changed to setSectionResizeMode.
[Line Number](https://github.com/QIICR/SlicerDevelopmentToolbox/blob/214ee9526e4a61d96a37e703513ab71553470e45/SlicerDevelopmentToolboxUtils/widgets.py#L269)

**Comment by che85** [comment]
Was fixed in https://github.com/QIICR/SlicerDevelopmentToolbox/commit/0e166810c0f4bccd2fd02715a1859a5089ab02da
